### PR TITLE
chore: add automated build/test workflow

### PR DESCRIPTION
**Pull request by jawnsy**

### CODE REVIEW

**Comment by Emyrk** [comment]
Can I approve this?

**Comment by jawnsy** [comment]
Oh... I should probably update this and split it up into two PRs. Why do you ask?

**Comment by Emyrk** [comment]
I'm adding a PR to this repo, and might need to add more changes. Or do them in `/m`'s test suite. It'd be easier to do in this repo.

**Review by Emyrk — APPROVED** [review]
CI has to start somewhere.

**Pull request merged**
